/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package module.api.client

import module.api.model.Something1DTO

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

internal open class Example1Api : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Returns a list of users.
     * Optional extended description in CommonMark or HTML.
     * @return kotlin.collections.List<Something1DTO>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun usersGet(): HttpResponse<kotlin.collections.List<Something1DTO>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<UsersGetResponse>().map { value }
    }

    @Serializable(UsersGetResponse.Companion::class)
    private class UsersGetResponse(val value: List<Something1DTO>) {
        companion object : KSerializer<UsersGetResponse> {
            private val serializer: KSerializer<List<Something1DTO>> = serializer<List<Something1DTO>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: UsersGetResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = UsersGetResponse(serializer.deserialize(decoder))
        }
    }
}
