name: Pull-Request Precheck

on:
  pull_request:
    types: [opened, synchronize, edited, reopened, assigned, unassigned]
    branches:
      - main
      - release/*
jobs:
  pull-request-precheck:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/kotlin@1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
